"""empty message

Revision ID: 1faf4acfedcc
Revises: None
Create Date: 2015-08-13 19:28:40.445934

"""

# revision identifiers, used by Alembic.
revision = '1faf4acfedcc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hack_news_posts')
    op.drop_table('hack_news_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hack_news_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hack_news_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('domain', sa.VARCHAR(length=120), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['username'], [u'hack_news_users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
